# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20170201_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='pratieleira',
            new_name='prateleira',
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together=set([('lote', 'prateleira')]),
        ),
    ]
